- service: blogger
  href: https://geek.daohoangson.com/
  username: geek.
  fa: laptop

- service: github
  href: https://github.com/daohoangson
  username: daohoangson
  fa: github-alt

- service: linkedin
  href: https://vn.linkedin.com/in/sondh
  username: sondh
  fa: linkedin-square

- service: stack-overflow
  href: https://stackoverflow.com/users/308114/mrpaint
  username: mrpaint
  fa: stack-overflow

- service: tumblr
  href: https://blog.daohoangson.com
  username: blog.
  fa: tumblr

- service: twitter
  href: https://twitter.com/mrpaint
  username: mrpaint
  fa: twitter
