- service: blogger
  href: http://geek.daohoangson.com/
  username: geek.
  fa: laptop

- service: facebook
  href: https://www.facebook.com/sondh
  username: sondh
  fa: facebook-official

- service: foursquare
  href: https://foursquare.com/mrpaint
  username: foursquare
  fa: foursquare

- service: github
  href: https://github.com/daohoangson
  username: daohoangson
  fa: github-alt

- service: hacker-news
  href: https://news.ycombinator.com/user?id=sondh
  username: sondh
  fa: hacker-news

- service: instagram
  href: https://instagram.com/sondh
  username: sondh
  fa: instagram

- service: linkedin
  href: https://vn.linkedin.com/in/sondh
  username: sondh
  fa: linkedin-square

- service: reddit
  href: https://www.reddit.com/user/mrpaint
  username: mrpaint
  fa: reddit-square

- service: stack-overflow
  href: https://stackoverflow.com/users/308114/mrpaint
  username: mrpaint
  fa: stack-overflow

- service: tumblr
  href: http://blog.daohoangson.com
  username: blog.
  fa: tumblr

- service: twitter
  href: https://twitter.com/mrpaint
  username: mrpaint
  fa: twitter

- service: youtube
  href: https://www.youtube.com/user/shmiluvu
  username: shmiluvu
  fa: youtube
