- service: blogger
  href: http://geek.daohoangson.com/
  username: geek.
  fa: blogger

- service: facebook
  href: https://www.facebook.com/sondh
  username: sondh
  fa: facebook-square

- service: github
  href: https://github.com/daohoangson
  username: daohoangson
  fa: github-square

- service: instagram
  href: https://instagram.com/sondh
  username: sondh
  fa: instagram-square

- service: linkedin
  href: https://vn.linkedin.com/in/sondh
  username: sondh
  fa: linkedin

- service: stack-overflow
  href: https://stackoverflow.com/users/308114/mrpaint
  username: mrpaint
  fa: stack-overflow

- service: tumblr
  href: http://blog.daohoangson.com
  username: blog.
  fa: tumblr-square

- service: twitter
  href: https://twitter.com/mrpaint
  username: mrpaint
  fa: twitter-square
